name: Minha primeira pipeline

on:
  push:
  pull_request:

jobs:
  teste:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Testar pipeline
        run: echo "Pipeline funcionando!"

      - name: Mostrar mensagem
        run: echo "Olá, GitHub Actions!"